//! SQLite schema definitions and initialization

use crate::error::Result;
use rusqlite::Connection;

/// Initialize the database schema
pub fn initialize_schema(conn: &Connection) -> Result<()> {
    // Enable WAL mode for better concurrency
    conn.execute_batch("PRAGMA journal_mode=WAL;")?;

    // FULL: fsync each WAL frame before commit. Prevents DB corruption on OS crash
    // at the cost of slightly higher write latency. NORMAL is faster but can corrupt
    // the DB on power loss or OS crash during a WAL checkpoint.
    conn.execute_batch("PRAGMA synchronous=FULL;")?;

    // Create logs table
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp INTEGER NOT NULL,
            observed_timestamp INTEGER,
            trace_id TEXT,
            span_id TEXT,
            severity_number INTEGER NOT NULL,
            severity_text TEXT,
            body TEXT NOT NULL,
            attributes TEXT,
            resource TEXT,
            scope TEXT,
            flags INTEGER,
            created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
        );",
    )?;

    // Create indexes for logs
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON logs(timestamp);
         CREATE INDEX IF NOT EXISTS idx_logs_severity ON logs(severity_number);
         CREATE INDEX IF NOT EXISTS idx_logs_trace_id ON logs(trace_id) WHERE trace_id IS NOT NULL;
         CREATE INDEX IF NOT EXISTS idx_logs_created_at ON logs(created_at);",
    )?;

    // Create spans table
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS spans (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            trace_id TEXT NOT NULL,
            span_id TEXT NOT NULL,
            parent_span_id TEXT,
            name TEXT NOT NULL,
            kind INTEGER NOT NULL,
            start_time INTEGER NOT NULL,
            end_time INTEGER NOT NULL,
            attributes TEXT,
            events TEXT,
            links TEXT,
            status_code INTEGER,
            status_message TEXT,
            resource TEXT,
            scope TEXT,
            flags INTEGER,
            created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
        );",
    )?;

    // Create indexes for spans
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_spans_trace_id ON spans(trace_id);
         CREATE INDEX IF NOT EXISTS idx_spans_span_id ON spans(span_id);
         CREATE INDEX IF NOT EXISTS idx_spans_start_time ON spans(start_time);
         CREATE INDEX IF NOT EXISTS idx_spans_end_time ON spans(end_time);
         CREATE INDEX IF NOT EXISTS idx_spans_parent_span_id ON spans(parent_span_id) WHERE parent_span_id IS NOT NULL;
         CREATE INDEX IF NOT EXISTS idx_spans_created_at ON spans(created_at);",
    )?;

    // Partial indexes for GenAI analytics. GenAI queries filter by a
    // json_extract OR-guard over `attributes`; without these indexes the
    // planner scans the whole time window (millions of rows) and evaluates
    // the guard per row. The guards are generated by the same semconv
    // functions the queries use, so index and query can never drift apart.
    // A partial index is only eligible when the query's WHERE contains the
    // index WHERE verbatim as a conjunct — which the reader queries do.
    {
        use otelite_core::semconv;
        let llm_guard = semconv::llm_span_guard("attributes");
        let request_guard = semconv::request_span_guard("attributes");
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_llm ON spans(start_time) WHERE {llm_guard}"
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_llm_request ON spans(start_time) WHERE {request_guard}"
            ),
            [],
        )?;
    }

    // Partial/expression indexes for the remaining analytics and detail
    // queries. Same drift-proof pattern as the GenAI guards above: the
    // predicates are generated by the same semconv functions the reader
    // queries embed in their WHERE clauses, and each query carries its
    // index predicate verbatim as a conjunct so the planner can use it.
    //
    // All predicates are total (json_valid-gated) because SQLite evaluates
    // partial-index predicates on every INSERT: a raising predicate would
    // reject telemetry batches containing a single corrupt row.
    {
        use otelite_core::semconv;
        let col = "attributes";
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_session_id \
                 ON spans({expr}) WHERE {pred}",
                expr = semconv::session_id_expr(col),
                pred = semconv::session_id_index_predicate(col)
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_finish_reason \
                 ON spans(start_time) WHERE {guard}",
                guard = semconv::finish_reason_guard(col)
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_tool \
                 ON spans(start_time) WHERE {guard}",
                guard = semconv::tool_span_guard(col)
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_retrieval \
                 ON spans(start_time) WHERE {guard}",
                guard = semconv::retrieval_span_guard(col)
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_tool_exec \
                 ON spans(start_time) WHERE name = '{name}'",
                name = semconv::TOOL_EXECUTION_SPAN_NAME
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_tool_approval \
                 ON spans(start_time) WHERE name = '{name}'",
                name = semconv::TOOL_APPROVAL_SPAN_NAME
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_llm_request_name \
                  ON spans(start_time) WHERE name = '{name}'",
                name = semconv::LLM_REQUEST_SPAN_NAME
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_spans_codex_handle_responses \
                  ON spans(start_time) WHERE name = '{name}'",
                name = semconv::CODEX_HANDLE_RESPONSES_SPAN_NAME
            ),
            [],
        )?;
        conn.execute(
            &format!(
                "CREATE INDEX IF NOT EXISTS idx_logs_api_body \
                 ON logs(timestamp) WHERE body = '{body}'",
                body = semconv::API_RESPONSE_BODY_LOG_BODY
            ),
            [],
        )?;
    }

    // Create metrics table
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS metrics (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            unit TEXT,
            metric_type INTEGER NOT NULL,
            timestamp INTEGER NOT NULL,
            value_int INTEGER,
            value_double REAL,
            value_histogram TEXT,
            value_summary TEXT,
            attributes TEXT,
            resource TEXT,
            scope TEXT,
            flags INTEGER,
            created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
        );",
    )?;

    // Create indexes for metrics
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_metrics_name ON metrics(name);
         CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp);
         CREATE INDEX IF NOT EXISTS idx_metrics_type ON metrics(metric_type);
         CREATE INDEX IF NOT EXISTS idx_metrics_created_at ON metrics(created_at);
         CREATE INDEX IF NOT EXISTS idx_metrics_name_ts ON metrics(name, timestamp);",
    )?;

    // Covering index for cumulative-counter windowed queries
    // (reader::counter_window_deltas): the per-series baseline lookup seeks by
    // the full label set + timestamp and reads the value without a table
    // fetch. The json_valid-gated expressions are total (NULL on missing or
    // malformed attributes), so evaluating them at INSERT time can never
    // raise and break ingestion. The reader's baseline query must use these
    // expressions verbatim for the index to be used (planner contract).
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_metrics_opencode_token_usage ON metrics(
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.agent') END,
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.model') END,
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.type') END,
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.\"session.id\"') END,
             timestamp, value_int)
          WHERE name = 'opencode.token.usage';",
    )?;

    // Covering indexes for the agent-rollup cumulative histogram counters
    // (reader::counter_window_deltas with a value expression): same
    // planner contract as idx_metrics_opencode_token_usage — the reader's
    // baseline seeks use these expressions verbatim. The histogram value
    // columns make the baseline seek index-only (no table fetch per
    // candidate row).
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_metrics_opencode_tool_duration ON metrics(
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.\"session.id\"') END,
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.tool_name') END,
             timestamp,
             CASE WHEN json_valid(value_histogram) THEN json_extract(value_histogram, '$[0]') END)
          WHERE name = 'opencode.tool.duration';",
    )?;
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_metrics_opencode_session_cost ON metrics(
             CASE WHEN json_valid(attributes) THEN json_extract(attributes, '$.\"session.id\"') END,
             timestamp,
             CASE WHEN json_valid(value_histogram) THEN json_extract(value_histogram, '$[1]') END)
          WHERE name = 'opencode.session.cost.total';",
    )?;

    // Create purge_history table
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS purge_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            start_time INTEGER NOT NULL,
            end_time INTEGER NOT NULL,
            logs_deleted INTEGER NOT NULL DEFAULT 0,
            spans_deleted INTEGER NOT NULL DEFAULT 0,
            metrics_deleted INTEGER NOT NULL DEFAULT 0
        );",
    )?;

    // Create index for purge_history
    conn.execute_batch(
        "CREATE INDEX IF NOT EXISTS idx_purge_history_start_time ON purge_history(start_time);",
    )?;

    // Create FTS5 full-text search table for logs
    conn.execute_batch(
        "CREATE VIRTUAL TABLE IF NOT EXISTS logs_fts USING fts5(
            body,
            content='logs',
            content_rowid='id'
        );",
    )?;

    // Create triggers to keep the FTS5 table in sync.
    //
    // `logs_fts` is an external-content table: it stores only the index,
    // and lookups join back into `logs`. Removing an index entry requires
    // the special FTS5 command form
    // `INSERT INTO logs_fts(logs_fts, rowid, body) VALUES ('delete', ...)`
    // — a plain `DELETE FROM logs_fts WHERE rowid = ...` is valid SQL but
    // matches nothing (the FTS table has no rows of its own) and silently
    // leaves orphaned entries behind, which is exactly what the pre-fix
    // triggers did.
    //
    // Migration: pre-fix builds shipped those no-op triggers and left
    // stale index entries behind. Detect them by the missing `'delete'`
    // command in the stored trigger SQL, replace the triggers, and rebuild
    // the index from the content table to drop the orphans. One-time cost,
    // proportional to log volume.
    let broken_fts_triggers = conn
        .query_row(
            "SELECT sql FROM sqlite_master
             WHERE type = 'trigger' AND name = 'logs_fts_delete'",
            [],
            |row| row.get::<_, String>(0),
        )
        .map(|sql| !sql.contains("'delete'"))
        .unwrap_or(false);

    if broken_fts_triggers {
        // Pre-fix builds shipped no-op delete/update triggers, so purged or
        // updated logs kept stale index entries. Replace the triggers (the
        // IF NOT EXISTS batch below recreates them with the correct SQL)
        // and rebuild the index from the content table to drop the
        // orphans. One-time cost, proportional to log volume.
        conn.execute_batch("DROP TRIGGER logs_fts_delete; DROP TRIGGER logs_fts_update;")?;
    }

    conn.execute_batch(
        "CREATE TRIGGER IF NOT EXISTS logs_fts_insert AFTER INSERT ON logs BEGIN
            INSERT INTO logs_fts(rowid, body) VALUES (new.id, new.body);
         END;

         CREATE TRIGGER IF NOT EXISTS logs_fts_delete AFTER DELETE ON logs BEGIN
            INSERT INTO logs_fts(logs_fts, rowid, body) VALUES ('delete', old.id, old.body);
         END;

         CREATE TRIGGER IF NOT EXISTS logs_fts_update AFTER UPDATE ON logs BEGIN
            INSERT INTO logs_fts(logs_fts, rowid, body) VALUES ('delete', old.id, old.body);
            INSERT INTO logs_fts(rowid, body) VALUES (new.id, new.body);
         END;",
    )?;

    if broken_fts_triggers {
        // Rebuild the index from the content table so the stale entries
        // left behind by the old triggers are dropped. A failure here
        // fails initialisation loudly; the triggers are already correct,
        // so only index hygiene (stale terms from updated logs) is at
        // stake on a retry.
        conn.execute("INSERT INTO logs_fts(logs_fts) VALUES ('rebuild')", [])?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::Connection;

    #[test]
    fn test_schema_initialization() {
        let conn = Connection::open_in_memory().unwrap();
        let result = initialize_schema(&conn);
        assert!(result.is_ok());
    }

    #[test]
    fn test_tables_created() {
        let conn = Connection::open_in_memory().unwrap();
        initialize_schema(&conn).unwrap();

        // Verify logs table exists
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='logs'")
            .unwrap();
        let exists = stmt.exists([]).unwrap();
        assert!(exists);

        // Verify spans table exists
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='spans'")
            .unwrap();
        let exists = stmt.exists([]).unwrap();
        assert!(exists);

        // Verify metrics table exists
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='metrics'")
            .unwrap();
        let exists = stmt.exists([]).unwrap();
        assert!(exists);

        // Verify purge_history table exists
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='purge_history'")
            .unwrap();
        let exists = stmt.exists([]).unwrap();
        assert!(exists);

        // Verify FTS5 table exists
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='logs_fts'")
            .unwrap();
        let exists = stmt.exists([]).unwrap();
        assert!(exists);
    }

    #[test]
    fn test_indexes_created() {
        let conn = Connection::open_in_memory().unwrap();
        initialize_schema(&conn).unwrap();

        // Verify at least one index exists for logs
        let mut stmt = conn
            .prepare("SELECT name FROM sqlite_master WHERE type='index' AND tbl_name='logs'")
            .unwrap();
        let count: i32 = stmt.query_map([], |_| Ok(1)).unwrap().count() as i32;
        assert!(count > 0);
    }

    #[test]
    fn test_fts5_triggers_created() {
        let conn = Connection::open_in_memory().unwrap();
        initialize_schema(&conn).unwrap();

        // Verify FTS5 triggers exist
        let mut stmt = conn
            .prepare(
                "SELECT name FROM sqlite_master WHERE type='trigger' AND name LIKE 'logs_fts_%'",
            )
            .unwrap();
        let count: i32 = stmt.query_map([], |_| Ok(1)).unwrap().count() as i32;
        assert_eq!(count, 3); // insert, delete, update triggers
    }
}
